const Database=require('better-sqlite3');const crypto=require('crypto');const path=require('path');const jwt=require('jsonwebtoken');
const db=new Database(process.env.DB_PATH||path.join(__dirname,'mkpos.db'));db.pragma('journal_mode=WAL');db.pragma('foreign_keys=ON');
const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),q=(s,...a)=>db.prepare(s).get(...a),all=(s,...a)=>db.prepare(s).all(...a);
const SECRET=process.env.JWT_SECRET||'mkpos-change-this-secret';
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Login required'});try{req.user=jwt.verify(h.slice(7),SECRET);next()}catch{return res.status(401).json({error:'Invalid session'})}}
const mg=(req,res,next)=>['admin','owner'].includes(req.user?.role)?next():res.status(403).json({error:'Management permission required'});
function audit(u,a,e,i,d=''){try{db.prepare('INSERT INTO audit VALUES(?,?,?,?,?,?,?)').run(id(),u,a,e,i,d,now())}catch{}}
module.exports=app=>{
 db.exec(`CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,name TEXT UNIQUE,type TEXT,opening_balance REAL DEFAULT 0,balance REAL DEFAULT 0,active INTEGER DEFAULT 1,created_at TEXT);CREATE TABLE IF NOT EXISTS ledger_entries(id TEXT PRIMARY KEY,account_id TEXT,entry_type TEXT,amount REAL,reference_type TEXT DEFAULT '',reference_id TEXT DEFAULT '',description TEXT DEFAULT '',created_at TEXT,user_id TEXT);CREATE TABLE IF NOT EXISTS transfers(id TEXT PRIMARY KEY,from_account TEXT,to_account TEXT,amount REAL,description TEXT DEFAULT '',created_at TEXT,user_id TEXT);CREATE TABLE IF NOT EXISTS shifts(id TEXT PRIMARY KEY,user_id TEXT,start_at TEXT,end_at TEXT,status TEXT DEFAULT 'open',opening_cash REAL DEFAULT 0,closing_cash REAL,expected_cash REAL DEFAULT 0,difference REAL DEFAULT 0);CREATE TABLE IF NOT EXISTS attendance(id TEXT PRIMARY KEY,user_id TEXT,clock_in TEXT,clock_out TEXT,status TEXT DEFAULT 'present',note TEXT DEFAULT '');CREATE TABLE IF NOT EXISTS reservations(id TEXT PRIMARY KEY,customer_id TEXT,table_id TEXT,reserved_at TEXT,party_size INTEGER DEFAULT 1,status TEXT DEFAULT 'booked',notes TEXT DEFAULT '',created_at TEXT,user_id TEXT);CREATE TABLE IF NOT EXISTS supplier_ledger(id TEXT PRIMARY KEY,supplier_id TEXT,type TEXT,amount REAL,reference_id TEXT DEFAULT '',description TEXT DEFAULT '',created_at TEXT,user_id TEXT);CREATE TABLE IF NOT EXISTS customer_points(id TEXT PRIMARY KEY,customer_id TEXT,points REAL,source TEXT,reference_id TEXT DEFAULT '',created_at TEXT);CREATE TABLE IF NOT EXISTS rider_locations(id TEXT PRIMARY KEY,rider_id TEXT,lat REAL,lng REAL,accuracy REAL,recorded_at TEXT);CREATE TABLE IF NOT EXISTS ai_actions(id TEXT PRIMARY KEY,action_type TEXT,status TEXT,reason TEXT,payload TEXT,created_at TEXT,user_id TEXT);CREATE TABLE IF NOT EXISTS day_closings(id TEXT PRIMARY KEY,business_date TEXT UNIQUE,closed_at TEXT,user_id TEXT,total_sales REAL,total_expenses REAL,total_cogs REAL,net_profit REAL,cash_expected REAL,cash_counted REAL,difference REAL);`);
app.get('/api/premium/overview',auth,mg,(req,res)=>{const sales=Number(q("SELECT COALESCE(SUM(total),0) x FROM orders WHERE payment_status='paid'").x),expenses=Number(q('SELECT COALESCE(SUM(amount),0) x FROM expenses').x),cogs=Number(q("SELECT COALESCE(SUM(sm.qty*CASE WHEN sm.unit_cost>0 THEN sm.unit_cost ELSE i.cost END),0) x FROM stock_movements sm LEFT JOIN inventory_items i ON i.id=sm.item_id WHERE sm.type='out' AND sm.reference_type='order'").x);res.json({sales,expenses,cogs,profit:sales-expenses-cogs,today:q("SELECT COALESCE(SUM(total),0) sales,COUNT(*) orders FROM orders WHERE payment_status='paid' AND date(created_at)=date('now','localtime')"),low:all('SELECT * FROM inventory_items WHERE active=1 AND current_stock<=reorder_level ORDER BY current_stock'),staff:all('SELECT id,name,username,role,active FROM users ORDER BY role,name')})});
app.get('/api/premium/transactions',auth,mg,(req,res)=>res.json(all('SELECT o.*,c.name customer_name,u.name waiter_name,r.name rider_name FROM orders o LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN users u ON u.id=o.waiter_id LEFT JOIN users r ON r.id=o.rider_id ORDER BY o.created_at DESC LIMIT 5000')));
app.get('/api/premium/order/:id',auth,(req,res)=>{const o=q('SELECT * FROM orders WHERE id=?',req.params.id);if(!o)return res.status(404).json({error:'Order not found'});res.json({order:o,items:all('SELECT * FROM order_items WHERE order_id=?',o.id),audit:all('SELECT a.*,u.name user_name FROM audit a LEFT JOIN users u ON u.id=a.user_id WHERE a.entity=? AND a.entity_id=? ORDER BY a.created_at','order',o.id)})});
app.get('/api/premium/staff-performance',auth,mg,(req,res)=>res.json(all("SELECT u.id,u.name,u.username,u.role,u.active,COUNT(DISTINCT a.id) actions,COUNT(DISTINCT CASE WHEN o.payment_status='paid' THEN o.id END) paid_orders,COALESCE(SUM(CASE WHEN o.payment_status='paid' THEN o.total ELSE 0 END),0) revenue FROM users u LEFT JOIN audit a ON a.user_id=u.id AND a.created_at>=datetime('now','-30 day') LEFT JOIN orders o ON (o.waiter_id=u.id OR o.rider_id=u.id) AND o.created_at>=datetime('now','-30 day') GROUP BY u.id ORDER BY actions DESC,revenue DESC")));
app.post('/api/premium/shifts/open',auth,(req,res)=>{const old=q("SELECT id FROM shifts WHERE user_id=? AND status='open'",req.user.id);if(old)return res.status(400).json({error:'Shift already open'});const x={id:id(),user_id:req.user.id,start_at:now(),end_at:null,status:'open',opening_cash:Number(req.body.opening_cash||0),closing_cash:null,expected_cash:0,difference:0};db.prepare('INSERT INTO shifts VALUES(?,?,?,?,?,?,?,?,?)').run(...Object.values(x));audit(req.user.id,'OPEN_SHIFT','shift',x.id);res.json(x)});
app.get('/api/premium/shifts',auth,mg,(req,res)=>res.json(all('SELECT s.*,u.name user_name,u.role FROM shifts s LEFT JOIN users u ON u.id=s.user_id ORDER BY start_at DESC LIMIT 1000')));
app.post('/api/premium/shifts/:id/close',auth,(req,res)=>{const s=q('SELECT * FROM shifts WHERE id=?',req.params.id);if(!s)return res.status(404).json({error:'Shift not found'});if(req.user.id!==s.user_id&&!['admin','owner'].includes(req.user.role))return res.status(403).json({error:'Cannot close this shift'});const expected=Number(s.opening_cash||0)+Number(q("SELECT COALESCE(SUM(total),0) x FROM orders WHERE payment_status='paid' AND created_at>=?",s.start_at).x),counted=Number(req.body.cash_counted||0),difference=counted-expected;db.prepare("UPDATE shifts SET end_at=?,status='closed',closing_cash=?,expected_cash=?,difference=? WHERE id=?").run(now(),counted,expected,difference,s.id);audit(req.user.id,'CLOSE_SHIFT','shift',s.id,JSON.stringify({expected,counted,difference}));res.json({expected,counted,difference})});
app.post('/api/premium/attendance/clock',auth,(req,res)=>{const open=q('SELECT * FROM attendance WHERE user_id=? AND clock_out IS NULL ORDER BY clock_in DESC LIMIT 1',req.user.id);if(open){db.prepare('UPDATE attendance SET clock_out=? WHERE id=?').run(now(),open.id);return res.json({status:'clocked_out'})}const x={id:id(),user_id:req.user.id,clock_in:now(),clock_out:null,status:'present',note:req.body.note||''};db.prepare('INSERT INTO attendance VALUES(?,?,?,?,?,?)').run(...Object.values(x));res.json({status:'clocked_in'})});
app.get('/api/premium/attendance',auth,mg,(req,res)=>res.json(all('SELECT a.*,u.name user_name,u.role FROM attendance a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.clock_in DESC LIMIT 5000')));
